[build-system]
requires = ["uv_build>=0.12.7,<0.13"]
build-backend = "uv_build"

[project]
name = "swissclock"
version = "0.1.0"
description = "A Swiss Railways inspired unified analog clock and morphing digital stopwatch"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Alin Elena", email = "alin@elena.re" }
]
requires-python = ">=3.8"
dependencies = [
    "PySide6>=6.0.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-qt",
    "pytest-cov",
    "ruff",
    "coveralls"
]

[project.scripts]
swissclock = "swissclock.main:main"

[tool.coverage.run]
source = ["swissclock"]

[tool.coverage.paths]
source = [
    "src/swissclock",
    ".tox/*/lib/python*/site-packages/swissclock",
]
