[tox]
envlist = py311, py312, py313, py314, py315
isolated_build = True

[testenv]
passenv = DISPLAY, XAUTHORITY, WAYLAND_DISPLAY, GITHUB_*
extras = test
commands =
    ruff check src tests
    pytest --cov=swissclock --cov-report=xml
